import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sidebar,
}: {
  children: React.ReactNode;
  sidebar: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link className="mr-4" href="/">
            Home
          </Link>
          <Link className="mr-4" href="/nested">
            Nested
          </Link>
          <Link className="mr-4" href="/nested/deeper">
            Nested Deeper
          </Link>
        </nav>
        {sidebar}
        {children}
      </body>
    </html>
  );
}
